export const dashboardStats = {
  totalEmployees: 312,
  activeProjects: 45,
  pendingRequests: 12,
  overallAttendance: "98%",
};

export const employees = [
  {
    id: "E1023",
    name: "Rohan Sharma",
    department: "Engineering",
    role: "Sr. Developer",
    location: "Bengaluru",
    status: "Active",
    photoUrl: "",
  },
  {
    id: "E1045",
    name: "Priya Nair",
    department: "HR",
    role: "Manager",
    location: "Mumbai",
    status: "Active",
    photoUrl: "",
  },
  {
    id: "E1088",
    name: "Arjun Verma",
    department: "Sales",
    role: "Sales Rep",
    location: "Delhi",
    status: "Active",
    photoUrl: "",
  },
  {
    id: "E1027",
    name: "Karan Mehta",
    department: "Engineering",
    role: "Sr. Developer",
    location: "Pune",
    status: "Active",
    photoUrl: "",
  },
  {
    id: "E1036",
    name: "Ananya Iyer",
    department: "Marketing",
    role: "Marketing Lead",
    location: "Hyderabad",
    status: "On Leave",
    photoUrl: "",
  },
  {
    id: "E1052",
    name: "Vikram Singh",
    department: "Engineering",
    role: "Manager",
    location: "Bengaluru",
    status: "Active",
    photoUrl: "",
  },
];
