export const dashboardStats = {
  totalEmployees: 312,
  activeProjects: 45,
  pendingRequests: 12,
  overallAttendance: "98%",
};

export const employees = [
  {
    id: "E1023",
    name: "Mark Chen",
    department: "Engineering",
    role: "Sr. Developer",
    location: "NYC",
    status: "Active",
    photoUrl: "",
  },
  {
    id: "E1045",
    name: "Aisha Khan",
    department: "HR",
    role: "Manager",
    location: "SF",
    status: "Active",
    photoUrl: "",
  },
  {
    id: "E1088",
    name: "John Smith",
    department: "Sales",
    role: "Rep",
    location: "Chicago",
    status: "Active",
    photoUrl: "",
  },
  {
    id: "E1027",
    name: "Mark Walnson",
    department: "Engineering",
    role: "Sr. Developer",
    location: "NYC",
    status: "Active",
    photoUrl: "",
  },
  {
    id: "E1036",
    name: "Nalva Wilson",
    department: "Marketing",
    role: "Sr. Developer",
    location: "Chicago",
    status: "On Leave",
    photoUrl: "",
  },
  {
    id: "E1045",
    name: "Assh Khan",
    department: "Engineering",
    role: "Manager",
    location: "NYC",
    status: "Active",
    photoUrl: "",
  },
];
